### ISSUE TITLE
Still Active?

### ISSUE THREAD

**Issue by jpjpjp** [joehoyle/monzo-to-lunch-money#18]
Hi, I'm JP, the Developer Advocate for Lunch Money.  I'm working on an [awesome-lunchmoney](https://github.com/jpjpjp/awesome-lunchmoney) collection of Lunch Money apps and projects.

Would you like your repo to be included?   This may attract members of the Lunch Money community to your repo.  If so, are you available to answer questions and provide help?

I'm happy to include this but I wanted to check in with you first and see if this is something that you want.

**Comment by joehoyle** [comment]
Hey @jpjpjp, this is pretty dormant as I'm not using it currently. I would say the code is there if anyone wants to learn from it, but it's not an active / supported project. Perhaps there's a space for inactive projects?

**Comment by jpjpjp** [comment]
Thanks for the quick response!    Feel free to close this issue!

Your repo is still listed in the v1 API Docs in the Awesome Projects directory, so people can find it there.
